/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OtpRequest"];
                };
            };
            responses: {
                /** @description Code sent */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OtpRequested"];
                    };
                };
                400: components["responses"]["Error"];
                429: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OtpVerify"];
                };
            };
            responses: {
                /** @description Signed in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                400: components["responses"]["Error"];
                403: components["responses"]["Error"];
                429: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Account */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                401: components["responses"]["Error"];
                429: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Market summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MarketResponse"];
                    };
                };
                401: components["responses"]["Error"];
                429: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ticker: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Quote detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuoteResponse"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/{ticker}/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    res?: "5s" | "1m" | "1d";
                    /** @description ISO-8601 or epoch ms */
                    from?: string;
                    /** @description ISO-8601 or epoch ms */
                    to?: string;
                    limit?: number;
                };
                header?: never;
                path: {
                    ticker: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Candles */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CandlesResponse"];
                    };
                };
                400: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** News, newest first. With a ticker, also market-wide and same-sector news. */
        get: {
            parameters: {
                query?: {
                    ticker?: string;
                    /** @description Only items with a smaller id (paging back) */
                    before?: number;
                    /** @description Only items with a larger id (catching up) */
                    after?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description News */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NewsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Upcoming earnings, dividends, splits, deal closes, IPOs and rate decisions (next 60 game days) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Calendar */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalendarResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The player's portfolio (opens the trading account with starting cash on first use) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Portfolio */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Portfolio"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    status?: "open" | "all";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Orders */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Order"][];
                    };
                };
            };
        };
        put?: never;
        /** Place an order (queued; executes at a future tick) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlaceOrderRequest"];
                };
            };
            responses: {
                /** @description Queued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlaceOrderResponse"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel an open order (or a whole order group) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cancelled */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Fills */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Fill"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** WebSocket price feed (signed via query parameters; see docs/API.md) */
        get: {
            parameters: {
                query: {
                    session: string;
                    ts: number;
                    nonce: string;
                    sig: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Switching protocols */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorBody: {
            error: string;
            message: string;
        };
        OtpRequest: {
            /** Format: email */
            email: string;
        };
        OtpRequested: {
            /** @description Pass to /otp/verify. Known only to the requester. */
            challengeId: string;
            /** Format: date-time */
            expiresAt: string;
            /** @description Only in dev mode or while a fixed code is configured */
            devCode?: string;
        };
        OtpVerify: {
            challengeId: string;
            code: string;
            /** @description base64url SPKI DER ECDSA P-256 public key */
            publicKey: string;
        };
        LoginResponse: {
            sessionId: string;
            /** Format: int64 */
            accountId: number;
            /** Format: date-time */
            expiresAt: string;
            /** Format: int64 */
            serverTime: number;
        };
        Badge: {
            badge: string;
            title: string;
            description: string;
            count: number;
            /** Format: date-time */
            lastAwardedAt: string;
        };
        MeResponse: {
            /** Format: int64 */
            accountId: number;
            email: string;
            /** Format: date-time */
            createdAt: string;
            badges: components["schemas"]["Badge"][];
        };
        SessionInfo: {
            /** @enum {string} */
            state: "OPEN" | "CLOSED";
            /** @enum {string|null} */
            kind?: "WEEKDAY_A" | "WEEKDAY_B" | "WEEKEND" | null;
            /** Format: date-time */
            opensAt?: string | null;
            /** Format: date-time */
            closesAt?: string | null;
            /** Format: date-time */
            nextOpen?: string | null;
            nextKind?: string | null;
        };
        Quote: {
            ticker: string;
            name: string;
            sector: string;
            /** Format: int64 */
            last: number;
            /** Format: int64 */
            bid?: number | null;
            /** Format: int64 */
            ask?: number | null;
            /** Format: int64 */
            bidSize?: number | null;
            /** Format: int64 */
            askSize?: number | null;
            /** Format: int64 */
            prevClose?: number | null;
            /** Format: int64 */
            open?: number | null;
            /** Format: int64 */
            high?: number | null;
            /** Format: int64 */
            low?: number | null;
            /** Format: int64 */
            volume: number;
            /** Format: int64 */
            change?: number | null;
            changePct?: number | null;
            /**
             * Format: int64
             * @description Dollars
             */
            marketCap: number;
        };
        IndexQuote: {
            name: string;
            value: number;
            prevClose?: number | null;
            change?: number | null;
            changePct?: number | null;
        };
        DepthLevel: {
            /** Format: int64 */
            price: number;
            /** Format: int64 */
            size: number;
        };
        Depth: {
            bids: components["schemas"]["DepthLevel"][];
            asks: components["schemas"]["DepthLevel"][];
        };
        Candle: {
            /** Format: date-time */
            time: string;
            /** Format: int64 */
            open: number;
            /** Format: int64 */
            high: number;
            /** Format: int64 */
            low: number;
            /** Format: int64 */
            close: number;
            /** Format: int64 */
            volume: number;
        };
        LegRequest: {
            /** @enum {string} */
            side: "BUY" | "SELL";
            /** Format: int64 */
            quantity: number;
            /** @enum {string} */
            type: "MARKET" | "LIMIT" | "STOP" | "STOP_LIMIT" | "TRAILING_STOP" | "TRAILING_STOP_LIMIT" | "TWAP" | "VWAP";
            /** Format: int64 */
            limitPrice?: number | null;
            /** Format: int64 */
            stopPrice?: number | null;
            /** Format: int64 */
            trailAmount?: number | null;
            trailPercent?: number | null;
            /** Format: int64 */
            limitOffset?: number | null;
            /**
             * @default DAY
             * @enum {string}
             */
            timeInForce: "DAY" | "GTC" | "IOC";
            /** @description TWAP/VWAP execution window */
            durationMinutes?: number | null;
        };
        PlaceOrderRequest: {
            ticker: string;
            /**
             * @default SINGLE
             * @enum {string}
             */
            structure: "SINGLE" | "OCO" | "OTO" | "BRACKET";
            legs: components["schemas"]["LegRequest"][];
        };
        PlaceOrderResponse: {
            /** Format: int64 */
            groupId: number;
            orderIds: number[];
            status: string;
            /** Format: date-time */
            executesAt?: string | null;
        };
        Order: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            groupId: number;
            ticker: string;
            side: string;
            type: string;
            /** Format: int64 */
            quantity: number;
            /** Format: int64 */
            filled: number;
            avgPrice?: number | null;
            /** Format: int64 */
            limitPrice?: number | null;
            /** Format: int64 */
            stopPrice?: number | null;
            /** @enum {string} */
            status: "WAITING" | "QUEUED" | "ARMED" | "WORKING" | "FILLED" | "CANCELLED" | "EXPIRED" | "REJECTED";
            reason?: string | null;
            liquidation: boolean;
            /** Format: date-time */
            updatedAt: string;
        };
        Fill: {
            id: string;
            /** Format: int64 */
            orderId: number;
            ticker: string;
            side: string;
            /** Format: int64 */
            quantity: number;
            /** Format: int64 */
            price: number;
            /** Format: int64 */
            commission: number;
            /** Format: int64 */
            realized: number;
            maker: boolean;
            liquidation: boolean;
            /** Format: date-time */
            at: string;
        };
        Position: {
            ticker: string;
            /**
             * Format: int64
             * @description Negative for shorts
             */
            quantity: number;
            /** @description Cents */
            avgPrice: number;
            /** Format: int64 */
            last: number;
            /** Format: int64 */
            marketValue: number;
            /** Format: int64 */
            unrealized: number;
            unrealizedPct: number;
            /** Format: int64 */
            dayChange?: number | null;
        };
        Notice: {
            /** Format: int64 */
            seq: number;
            kind: string;
            text: string;
            /** Format: date-time */
            at: string;
        };
        Portfolio: {
            /** Format: int64 */
            accountId: number;
            /** @enum {string} */
            plan: "ROOKIE" | "TRADER" | "PRO" | "WHALE";
            /**
             * Format: int64
             * @description Negative = margin loan
             */
            cash: number;
            /** Format: int64 */
            equity: number;
            /** Format: int64 */
            longValue: number;
            /** Format: int64 */
            shortValue: number;
            /** Format: int64 */
            availableEquity: number;
            /** Format: int64 */
            buyingPower: number;
            /** Format: int64 */
            marginDebt: number;
            /** Format: int64 */
            maintenanceRequirement: number;
            initialMargin: number;
            maintenanceMargin: number;
            /** Format: int64 */
            lifetimeRealized: number;
            /** Format: int64 */
            commissionsPaid: number;
            /** Format: int64 */
            interestPaid: number;
            positions: components["schemas"]["Position"][];
            openOrders: components["schemas"]["Order"][];
            notices: components["schemas"]["Notice"][];
        };
        NewsItem: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            time: string;
            /** @description Game day */
            day: number;
            /** @description Null for market-wide or sector news */
            ticker: string | null;
            sector: string | null;
            /** @enum {string} */
            category: "EARNINGS" | "DIVIDEND" | "CORPORATE" | "REGULATORY" | "LEGAL" | "ANALYST" | "RUMOR" | "SECTOR" | "MACRO" | "DEAL" | "LISTING" | "SPLIT" | "DISTRESS";
            headline: string;
            /** @enum {string} */
            tone: "positive" | "negative" | "neutral";
        };
        NewsResponse: {
            news: components["schemas"]["NewsItem"][];
        };
        CalendarEvent: {
            /**
             * Format: date-time
             * @description Session open
             */
            date: string;
            day: number;
            /** @enum {string} */
            kind: "EARNINGS" | "EX_DIVIDEND" | "DIVIDEND_PAY" | "SPLIT" | "DEAL_CLOSE" | "IPO" | "RATE_DECISION";
            ticker: string | null;
            name: string | null;
            detail: string;
        };
        Delisting: {
            ticker: string;
            name: string;
            day: number;
            /**
             * Format: int64
             * @description Settlement price (0 = bankruptcy)
             */
            price: number;
            reason: string;
        };
        CalendarResponse: {
            /** @description Percent */
            benchmarkRate: number;
            events: components["schemas"]["CalendarEvent"][];
            delistings: components["schemas"]["Delisting"][];
        };
        Fundamentals: {
            /** Format: int64 */
            shares: number;
            /** Format: int64 */
            epsTtm: number | null;
            pe: number | null;
            /**
             * Format: int64
             * @description Quarterly
             */
            dividend: number;
            /** @description Annual */
            dividendYield: number | null;
            /** Format: date-time */
            exDividendDate: string | null;
            /** Format: date-time */
            dividendPayDate: string | null;
            /** Format: date-time */
            nextEarnings: string | null;
            /** Format: int64 */
            consensusEps: number;
            /** @enum {string} */
            status: "ACTIVE" | "DISTRESS" | "DEAL_PENDING";
            /** Format: int64 */
            dealOffer: number | null;
            /** Format: date-time */
            splitDate: string | null;
            /** @description New shares per old share */
            splitRatio: number | null;
            /** Format: int64 */
            shortInterest: number;
            shortInterestPct: number;
            /** @description Annual */
            borrowFee: number;
        };
        MarketResponse: {
            /** @description Central bank rate */
            benchmarkRate: number;
            /** Format: int64 */
            latestNewsId: number;
            /** Format: date-time */
            time: string;
            session: components["schemas"]["SessionInfo"];
            /** @enum {string} */
            regime: "NEUTRAL" | "BULL" | "BEAR" | "CRASH" | "BUBBLE";
            index: components["schemas"]["IndexQuote"];
            quotes: components["schemas"]["Quote"][];
        };
        QuoteResponse: {
            /** Format: date-time */
            time: string;
            session: components["schemas"]["SessionInfo"];
            quote: components["schemas"]["Quote"];
            profile: {
                ticker: string;
                name: string;
                sector: string;
                /** Format: int64 */
                sharesOutstanding: number;
            };
            stats: {
                /** Format: int64 */
                high52w?: number | null;
                /** Format: int64 */
                low52w?: number | null;
                /** Format: int64 */
                avgVolume30d?: number | null;
            };
            depth: components["schemas"]["Depth"];
            fundamentals: components["schemas"]["Fundamentals"];
        };
        CandlesResponse: {
            ticker: string;
            resolution: string;
            candles: components["schemas"]["Candle"][];
            live?: components["schemas"]["Candle"] | null;
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
