/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OtpRequest"];
                };
            };
            responses: {
                /** @description Code sent */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OtpRequested"];
                    };
                };
                400: components["responses"]["Error"];
                429: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OtpVerify"];
                };
            };
            responses: {
                /** @description Signed in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                400: components["responses"]["Error"];
                403: components["responses"]["Error"];
                429: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Account */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                401: components["responses"]["Error"];
                429: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Market summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MarketResponse"];
                    };
                };
                401: components["responses"]["Error"];
                429: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ticker: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Quote detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuoteResponse"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/{ticker}/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    res?: "5s" | "1m" | "1d";
                    /** @description ISO-8601 or epoch ms */
                    from?: string;
                    /** @description ISO-8601 or epoch ms */
                    to?: string;
                    limit?: number;
                };
                header?: never;
                path: {
                    ticker: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Candles */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CandlesResponse"];
                    };
                };
                400: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** WebSocket price feed (signed via query parameters; see docs/API.md) */
        get: {
            parameters: {
                query: {
                    session: string;
                    ts: number;
                    nonce: string;
                    sig: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Switching protocols */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorBody: {
            error: string;
            message: string;
        };
        OtpRequest: {
            /** Format: email */
            email: string;
        };
        OtpRequested: {
            /** Format: date-time */
            expiresAt: string;
            /** @description Only when the server runs in dev mode */
            devCode?: string;
        };
        OtpVerify: {
            email: string;
            code: string;
            /** @description base64url SPKI DER ECDSA P-256 public key */
            publicKey: string;
        };
        LoginResponse: {
            sessionId: string;
            /** Format: int64 */
            accountId: number;
            /** Format: date-time */
            expiresAt: string;
            newAccount: boolean;
            /** Format: int64 */
            serverTime: number;
        };
        Badge: {
            badge: string;
            title: string;
            description: string;
            count: number;
            /** Format: date-time */
            lastAwardedAt: string;
        };
        MeResponse: {
            /** Format: int64 */
            accountId: number;
            email: string;
            /** Format: date-time */
            createdAt: string;
            badges: components["schemas"]["Badge"][];
        };
        SessionInfo: {
            /** @enum {string} */
            state: "OPEN" | "CLOSED";
            /** @enum {string|null} */
            kind?: "WEEKDAY_A" | "WEEKDAY_B" | "WEEKEND" | null;
            /** Format: date-time */
            opensAt?: string | null;
            /** Format: date-time */
            closesAt?: string | null;
            /** Format: date-time */
            nextOpen?: string | null;
            nextKind?: string | null;
        };
        Quote: {
            ticker: string;
            name: string;
            sector: string;
            /** Format: int64 */
            last: number;
            /** Format: int64 */
            bid?: number | null;
            /** Format: int64 */
            ask?: number | null;
            /** Format: int64 */
            bidSize?: number | null;
            /** Format: int64 */
            askSize?: number | null;
            /** Format: int64 */
            prevClose?: number | null;
            /** Format: int64 */
            open?: number | null;
            /** Format: int64 */
            high?: number | null;
            /** Format: int64 */
            low?: number | null;
            /** Format: int64 */
            volume: number;
            /** Format: int64 */
            change?: number | null;
            changePct?: number | null;
            /**
             * Format: int64
             * @description Dollars
             */
            marketCap: number;
        };
        IndexQuote: {
            name: string;
            value: number;
            prevClose?: number | null;
            change?: number | null;
            changePct?: number | null;
        };
        DepthLevel: {
            /** Format: int64 */
            price: number;
            /** Format: int64 */
            size: number;
        };
        Depth: {
            bids: components["schemas"]["DepthLevel"][];
            asks: components["schemas"]["DepthLevel"][];
        };
        Candle: {
            /** Format: date-time */
            time: string;
            /** Format: int64 */
            open: number;
            /** Format: int64 */
            high: number;
            /** Format: int64 */
            low: number;
            /** Format: int64 */
            close: number;
            /** Format: int64 */
            volume: number;
        };
        MarketResponse: {
            /** Format: date-time */
            time: string;
            session: components["schemas"]["SessionInfo"];
            /** @enum {string} */
            regime: "NEUTRAL" | "BULL" | "BEAR" | "CRASH" | "BUBBLE";
            index: components["schemas"]["IndexQuote"];
            quotes: components["schemas"]["Quote"][];
        };
        QuoteResponse: {
            /** Format: date-time */
            time: string;
            session: components["schemas"]["SessionInfo"];
            quote: components["schemas"]["Quote"];
            profile: {
                ticker: string;
                name: string;
                sector: string;
                /** Format: int64 */
                sharesOutstanding: number;
            };
            stats: {
                /** Format: int64 */
                high52w?: number | null;
                /** Format: int64 */
                low52w?: number | null;
                /** Format: int64 */
                avgVolume30d?: number | null;
            };
            depth: components["schemas"]["Depth"];
        };
        CandlesResponse: {
            ticker: string;
            resolution: string;
            candles: components["schemas"]["Candle"][];
            live?: components["schemas"]["Candle"] | null;
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
